### ISSUE TITLE
Change relative package imports to absolute

### ISSUE THREAD

**Issue by jbkolze** [HydrologicEngineeringCenter/cwms-python#81]
Relative imports are causing issues when used as an Airflow plugin (different package, but same idea):

```
airflow-scheduler  | [2024-08-01T13:26:35.406+0000] {plugins_manager.py:285} ERROR - Failed to import plugin /opt/airflow/plugins/shef/__init__.py
airflow-scheduler  | Traceback (most recent call last):
airflow-scheduler  |   File "/home/airflow/.local/lib/python3.11/site-packages/airflow/plugins_manager.py", line 277, in load_plugins_from_plugin_directory
airflow-scheduler  |     loader.exec_module(mod)
airflow-scheduler  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
airflow-scheduler  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
airflow-scheduler  |   File "/opt/airflow/plugins/shef/__init__.py", line 2, in <module>
airflow-scheduler  |     from . import shef_parser
airflow-scheduler  | ImportError: attempted relative import with no known parent package
```

Recommend changing relative imports to absolute, so ```from .api import *``` would become ```from cwms.api import *```

**Comment by Enovotny** [comment]
made this change and change types to cwms_types to work with airflow.
